//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LedgerAng.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string AddedBy { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
